# MINOR PROJECT

In [ ]:
import pandas as pd
import numpy as num
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('mobile_price_range_data.csv')

In [ ]:
df.head

<bound method NDFrame.head of       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width

In [ ]:
df.shape

(2000, 21)

In [ ]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [ ]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
print(x.shape)
print(y.shape)


(2000, 20)
(2000,)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


In [ ]:
import warnings
warnings.filterwarnings('ignore')

## LOGISTIC REGRESSION

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
m1 = LogisticRegression()
m1.fit(x_train,y_train)

LogisticRegression()

In [ ]:
print('training acc score',m1.score(x_train,y_train))
print('testing acc score',m1.score(x_test,y_test))

training acc score 0.634
testing acc score 0.644


In [ ]:
y_pred_m1 = m1.predict(x_test)
print(y_pred_m1)

[1 1 1 1 3 2 3 2 3 0 1 3 0 2 3 1 1 2 3 2 0 3 0 0 0 1 1 2 2 0 1 2 0 1 1 0 3
 0 0 0 3 2 3 2 2 2 0 0 3 1 1 3 0 2 2 2 3 1 2 1 2 2 1 1 2 3 3 3 3 3 2 3 2 2
 1 3 1 3 2 2 2 2 1 2 2 0 0 1 3 3 2 1 1 3 3 0 0 0 1 2 0 1 2 1 3 0 1 3 0 1 3
 0 0 0 3 3 2 0 3 2 2 1 3 0 2 2 3 0 2 2 2 2 0 0 1 0 1 3 3 2 0 3 0 0 2 2 2 0
 1 3 3 2 0 2 0 0 2 2 1 1 1 0 1 0 1 2 3 3 1 2 0 3 2 3 2 0 3 3 2 2 0 3 2 3 2
 0 2 1 1 2 2 3 0 3 1 1 1 3 1 0 3 2 3 1 0 3 1 3 1 3 2 1 3 2 0 3 3 0 1 0 3 0
 2 0 3 2 3 2 1 3 1 2 2 1 1 3 0 0 0 0 0 1 0 1 2 0 3 1 2 0 3 3 1 1 2 0 0 0 2
 1 0 2 2 0 3 3 2 1 3 1 3 2 2 0 3 1 3 1 2 1 2 2 2 1 2 2 2 2 2 1 0 1 0 0 3 0
 3 2 2 1 0 2 1 3 3 3 0 2 1 2 2 1 0 1 2 3 1 3 3 3 3 1 3 2 0 1 0 1 0 0 0 3 1
 3 1 3 0 0 1 0 3 3 3 2 2 2 2 1 2 0 3 2 2 1 3 3 0 1 1 0 3 1 3 0 3 2 3 1 2 0
 1 1 2 2 0 1 1 2 0 3 3 3 1 3 2 1 2 1 3 1 1 0 3 3 2 2 3 1 0 1 2 0 3 0 1 3 3
 3 0 2 3 1 3 1 2 0 0 2 1 2 2 3 0 3 3 1 0 0 3 3 1 2 1 1 2 0 1 2 0 2 2 3 0 3
 2 3 1 3 1 3 3 3 3 2 0 2 2 1 2 1 0 2 1 1 0 0 1 1 0 0 2 1 2 1 3 3 3 2 0 0 2
 0 2 0 3 2 1 0 3 3 2 0 3 

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
cm = confusion_matrix(y_test,y_pred_m1)
print(cm)

[[91 25  3  0]
 [24 69 31  5]
 [ 0 25 68 33]
 [ 0  1 31 94]]


In [ ]:
print(classification_report(y_test,y_pred_m1))

              precision    recall  f1-score   support

           0       0.79      0.76      0.78       119
           1       0.57      0.53      0.55       129
           2       0.51      0.54      0.53       126
           3       0.71      0.75      0.73       126

    accuracy                           0.64       500
   macro avg       0.65      0.65      0.65       500
weighted avg       0.64      0.64      0.64       500



## KNN CLASSIFICATION

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
m2 = KNeighborsClassifier(n_neighbors=15)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [ ]:
print('Training score',m2.score(x_train,y_train))
print('Testing score',m2.score(x_test,y_test))

Training score 0.9426666666666667
Testing score 0.926


In [ ]:
y_pred_m2 = m2.predict(x_test)
print(y_pred_m2)

[1 1 0 2 3 3 2 2 3 0 1 3 0 1 3 2 0 1 2 2 1 3 0 0 1 2 0 0 3 1 2 3 0 1 0 0 2
 0 0 1 3 1 3 2 3 3 0 0 3 2 2 1 0 1 3 2 3 1 3 2 1 2 1 1 3 2 3 3 3 3 2 3 3 2
 0 2 1 3 3 3 1 2 2 3 2 0 0 1 3 2 1 0 1 3 3 1 0 0 1 2 1 1 1 0 2 0 2 3 0 2 3
 0 0 0 2 2 2 1 3 1 1 1 3 0 2 1 3 0 2 3 1 3 0 0 0 1 2 3 3 2 0 2 0 0 2 2 2 0
 0 2 2 1 1 3 0 0 3 2 0 1 1 1 1 0 1 3 3 3 1 2 0 2 3 3 3 0 2 3 3 2 0 3 2 2 2
 1 2 1 2 2 2 2 0 2 1 0 1 3 1 0 3 1 3 1 0 2 2 2 1 3 1 1 3 2 0 3 3 0 1 0 3 0
 2 0 3 3 2 2 1 3 1 3 1 1 0 3 1 0 0 0 0 1 0 0 3 0 1 1 3 0 3 3 1 1 0 0 0 0 2
 1 0 1 2 0 3 3 2 2 3 2 3 2 2 0 3 2 3 1 1 2 3 2 1 1 3 1 3 2 2 0 1 1 0 0 3 0
 3 3 2 1 1 1 0 3 2 3 0 3 0 2 1 2 0 1 2 2 1 3 3 3 2 1 2 2 1 0 0 1 0 1 0 3 1
 3 0 3 0 0 0 0 3 2 2 1 2 2 1 0 3 0 3 2 1 1 2 2 0 1 1 1 2 1 2 0 3 0 3 1 2 0
 1 2 1 2 0 1 2 2 0 3 2 3 2 1 1 1 2 1 3 1 0 0 3 3 3 2 3 2 0 0 2 0 1 0 1 3 3
 3 0 1 3 0 3 1 3 1 0 1 1 2 3 3 1 2 3 1 0 0 3 2 1 3 1 2 1 0 1 2 1 2 0 2 1 3
 1 3 1 3 1 3 3 1 3 2 0 2 1 2 3 2 0 3 0 1 0 0 3 0 0 0 2 1 2 1 2 3 3 3 0 0 2
 0 2 0 3 2 1 0 2 3 1 0 3 

In [ ]:
print(confusion_matrix(y_test,y_pred_m2))
print(classification_report(y_test,y_pred_m2))

[[118   1   0   0]
 [  7 118   4   0]
 [  0   7 109  10]
 [  0   0   8 118]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       119
           1       0.94      0.91      0.93       129
           2       0.90      0.87      0.88       126
           3       0.92      0.94      0.93       126

    accuracy                           0.93       500
   macro avg       0.93      0.93      0.93       500
weighted avg       0.93      0.93      0.93       500



## NAIVE BAYES CLASSIFIERS

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
mnb = MultinomialNB()
mnb.fit(x_train,y_train)

MultinomialNB()

In [ ]:
print('Training score',mnb.score(x_train,y_train))
print('Testing score',mnb.score(x_test,y_test))

Training score 0.528
Testing score 0.504


In [ ]:
y_pred_mnb = mnb.predict(x_test)
print(y_pred_mnb)

[0 1 0 2 3 3 3 2 2 0 2 3 1 2 2 1 2 3 3 1 0 3 0 0 0 2 0 2 2 0 1 3 0 0 0 0 3
 0 0 1 2 1 3 3 3 3 0 0 3 1 1 3 1 2 3 2 3 0 3 2 2 3 2 0 1 2 3 3 3 3 2 3 3 3
 0 3 3 3 3 3 2 3 1 2 1 0 0 0 3 3 3 0 1 3 3 0 1 0 1 3 0 2 2 0 3 0 1 3 1 1 3
 0 0 0 3 3 3 0 3 2 2 0 3 0 2 2 3 2 2 1 3 3 0 0 0 1 1 3 2 1 0 2 1 0 3 3 0 0
 0 3 3 2 0 2 0 0 2 3 1 1 2 1 1 0 1 2 3 3 1 3 0 3 1 3 3 0 1 3 3 3 0 2 3 3 2
 0 3 0 3 1 3 3 0 3 1 1 2 3 0 0 2 2 3 1 0 2 1 3 1 3 3 0 2 1 0 3 3 0 1 0 2 0
 3 0 2 3 1 3 2 3 2 3 1 2 1 3 0 1 1 0 0 1 0 0 2 0 3 0 3 0 3 3 1 0 2 0 0 0 1
 1 1 2 2 0 2 3 1 0 3 1 2 3 3 0 3 1 2 1 1 2 3 2 3 1 3 1 3 1 2 0 0 2 0 0 3 0
 3 2 2 2 1 2 0 2 3 3 0 3 1 2 3 2 0 2 2 3 1 3 3 3 3 1 3 2 0 0 0 0 0 0 1 2 1
 2 0 3 0 0 1 0 3 3 2 2 2 2 1 1 3 1 3 1 1 0 1 3 0 2 0 0 3 2 2 0 3 1 3 1 3 0
 1 1 1 3 1 2 2 1 0 3 1 3 1 3 2 3 2 2 3 2 2 1 3 3 3 3 3 1 1 1 2 0 3 0 2 3 3
 3 0 1 3 1 2 1 3 0 0 3 1 3 2 3 0 1 2 1 2 0 2 3 0 2 0 2 3 0 1 2 0 3 1 3 1 2
 3 3 0 2 1 3 3 1 3 1 0 2 2 2 2 1 0 3 1 0 0 0 1 2 1 0 1 0 3 0 3 3 2 1 0 0 1
 1 3 0 3 2 1 2 3 3 1 0 3 

In [ ]:
cm_mnb = confusion_matrix(y_test,y_pred_mnb)
print(cm_mnb)
print(classification_report(y_test,y_pred_mnb))

[[84 27  8  0]
 [41 42 30 16]
 [ 2 32 37 55]
 [ 0  7 30 89]]
              precision    recall  f1-score   support

           0       0.66      0.71      0.68       119
           1       0.39      0.33      0.35       129
           2       0.35      0.29      0.32       126
           3       0.56      0.71      0.62       126

    accuracy                           0.50       500
   macro avg       0.49      0.51      0.50       500
weighted avg       0.49      0.50      0.49       500



## SVM WITH DIFFERENT KERNELS

### LINEAR KERNEL

In [ ]:
from sklearn.svm import SVC

In [ ]:
m3 = SVC(kernel='linear')
m3.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))

Training score 0.9953333333333333
Testing score 0.97


In [ ]:
y_pred_m3 = m3.predict(x_test)
print(y_pred_m3)

[1 1 1 2 3 3 2 2 3 0 1 3 0 1 3 2 0 1 2 2 1 3 0 0 1 2 0 0 3 1 2 2 0 1 0 0 2
 0 0 1 3 1 3 2 3 3 0 0 3 2 2 1 0 2 2 2 3 1 2 2 1 2 1 1 3 2 3 3 3 3 2 3 2 2
 0 2 1 3 3 2 1 2 2 3 2 0 0 1 3 2 1 0 1 3 2 1 0 0 1 2 1 1 1 0 2 0 2 3 0 2 3
 0 0 0 2 3 3 1 3 1 2 1 3 0 2 1 3 0 2 3 1 3 0 0 0 1 2 3 3 2 0 2 0 0 2 2 2 0
 0 2 2 2 1 3 1 0 3 2 0 1 2 1 1 0 1 2 3 3 1 2 0 3 3 3 3 0 3 3 3 2 0 3 1 2 2
 1 2 1 2 2 2 2 1 3 1 0 1 3 1 0 3 1 3 1 0 2 2 2 1 3 1 2 3 2 0 3 3 0 1 0 3 0
 2 0 3 3 2 2 1 3 1 2 1 1 0 3 1 0 0 0 0 1 0 1 3 0 1 1 3 0 3 3 1 1 1 0 0 0 2
 1 0 1 1 0 3 2 3 2 3 2 3 2 2 0 3 2 3 2 1 2 3 2 1 1 3 1 3 2 2 0 1 1 0 0 3 1
 3 3 2 1 1 1 0 3 2 3 0 3 0 2 1 2 0 1 2 2 1 3 3 3 2 1 2 2 1 0 0 1 0 1 0 3 1
 3 0 3 0 0 1 0 3 2 2 1 2 2 1 0 2 0 3 2 1 1 2 2 0 1 1 1 2 1 3 0 3 0 3 1 2 0
 1 2 1 2 0 1 1 2 0 3 3 3 2 1 1 1 2 1 3 1 0 0 3 3 3 2 3 2 0 0 2 0 1 0 1 3 3
 3 0 1 3 0 3 1 3 0 0 1 1 2 3 3 1 2 3 1 0 0 3 3 1 3 1 2 1 0 1 2 1 2 0 2 1 3
 1 3 1 3 1 3 3 1 3 2 0 2 1 2 3 2 0 3 0 1 0 0 3 0 0 0 3 1 2 1 3 3 3 3 0 0 2
 0 2 0 3 2 1 0 2 3 1 0 3 

In [ ]:
cm_m3 = confusion_matrix(y_test,y_pred_m3)
print(cm_m3)
print(classification_report(y_test,y_pred_m3))

[[118   1   0   0]
 [  1 125   3   0]
 [  0   3 118   5]
 [  0   0   2 124]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       119
           1       0.97      0.97      0.97       129
           2       0.96      0.94      0.95       126
           3       0.96      0.98      0.97       126

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500



### RBF KERNEL

In [ ]:
mr = SVC(kernel='rbf')
mr.fit(x_train,y_train)

SVC()

In [ ]:
print('Training score',mr.score(x_train,y_train))
print('Testing score',mr.score(x_test,y_test))

Training score 0.9506666666666667
Testing score 0.958


In [ ]:
y_pred_mr = mr.predict(x_test)
print(y_pred_mr)

[1 1 0 2 3 3 2 2 3 0 1 3 0 1 3 2 0 1 2 2 1 3 0 0 1 2 0 0 3 1 2 3 0 1 0 0 2
 0 0 1 3 1 3 2 3 3 0 0 3 2 2 1 0 1 3 2 3 1 3 2 1 2 1 1 3 2 3 3 3 3 2 3 2 2
 0 2 1 3 3 3 1 2 1 3 2 0 0 1 3 2 1 0 1 3 3 1 0 0 1 2 1 1 1 0 2 0 2 3 0 2 3
 0 0 0 2 3 3 1 3 1 2 1 3 0 2 1 3 0 2 3 1 3 0 0 0 1 2 3 3 2 0 2 0 0 2 2 2 0
 0 2 2 2 0 3 1 0 3 2 0 1 2 1 1 0 1 3 3 3 1 2 0 3 3 3 3 0 2 3 3 2 0 3 1 2 2
 1 2 1 2 2 2 2 0 3 1 0 1 3 1 0 3 1 3 1 0 2 2 2 1 3 1 2 3 3 0 3 3 0 1 0 3 0
 2 0 3 3 2 2 1 3 1 2 1 1 0 3 1 0 0 0 0 1 0 1 3 0 1 1 3 0 3 3 1 1 1 0 0 0 2
 1 0 1 1 0 3 3 3 1 3 2 3 2 2 0 3 2 3 2 1 2 3 2 1 1 3 1 3 2 2 0 1 1 0 0 3 1
 3 3 2 1 1 1 0 3 2 3 0 3 0 2 1 2 0 1 2 2 0 3 3 3 2 1 2 2 1 0 0 1 0 1 0 3 1
 3 0 3 0 0 1 0 3 2 2 1 2 2 1 0 2 0 3 2 1 1 2 2 0 1 1 1 2 1 3 0 3 0 3 1 2 0
 1 2 1 2 0 1 2 2 0 3 2 3 2 1 1 1 2 1 3 1 0 0 3 3 3 2 3 2 0 0 2 0 1 0 1 3 3
 2 0 1 3 0 3 1 3 1 0 1 1 2 3 3 1 2 3 1 0 0 3 3 1 3 1 2 1 0 1 2 1 2 0 3 1 3
 1 3 1 3 1 3 3 1 3 2 0 2 1 2 3 2 0 3 0 1 0 0 3 1 0 0 3 1 2 1 3 3 3 3 0 0 2
 0 2 0 3 2 1 0 2 3 1 0 3 

In [ ]:
cm_mr = confusion_matrix(y_test,y_pred_mr)
print(cm_mr)
print(classification_report(y_test,y_pred_mr))

[[118   1   0   0]
 [  3 125   1   0]
 [  0   3 112  11]
 [  0   0   2 124]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       119
           1       0.97      0.97      0.97       129
           2       0.97      0.89      0.93       126
           3       0.92      0.98      0.95       126

    accuracy                           0.96       500
   macro avg       0.96      0.96      0.96       500
weighted avg       0.96      0.96      0.96       500



# REPORT

In [ ]:
print('ACCURACY SCORE OF LOGISTIC REGRESSION MODEL IS',accuracy_score(y_test,y_pred_m1))
print('ACCURACY SCORE OF KNN CLASSIFICATION MODEL IS',accuracy_score(y_test,y_pred_m2))
print('ACCURACY SCORE OF NAIVE BAYES MODEL IS',accuracy_score(y_test,y_pred_mnb))
print('ACCURACY SCORE OF SVM WITH LINEAR KERNEL IS',accuracy_score(y_test,y_pred_m3))
print('ACCURACY SCORE OF SVM WITH rbf KERNEL IS',accuracy_score(y_test,y_pred_mr))

ACCURACY SCORE OF LOGISTIC REGRESSION MODEL IS 0.644
ACCURACY SCORE OF KNN CLASSIFICATION MODEL IS 0.926
ACCURACY SCORE OF NAIVE BAYES MODEL IS 0.504
ACCURACY SCORE OF SVM WITH LINEAR KERNEL IS 0.97
ACCURACY SCORE OF SVM WITH rbf KERNEL IS 0.958


 <b>HENCE FROM THE ANALYSIS, SVM WITH LINEAR KERNEL IS THE MOST ACCURATE MODEL FOR THE GIVEN DATASET</b>